language: cpp
compiler: g++

before_install: 
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -y
install: 
 - sudo apt-get install -y g++-4.8 libgl1-mesa-dev freeglut3 freeglut3-dev libglew-dev libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev qt4-qmake qt-sdk libusb-1.0-0-dev flex bison

script: 
 - qmake -o build-usb-machine/Makefile 
 - cd build-usb-machine
 - make && make sub-tests
 - LD_LIBRARY_PATH=$(pwd)/lib:$LD_LIBRARY_PATH ./tests/tests
